server:
  port: 8083

spring:
  application:
    name: booking-service

  datasource:
    url: jdbc:mysql://localhost:3306/eventify_booking
    username: root
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:your-dev-secret-key}